export interface OrderVO {
  id: string | number;
  orderSn: string;
  buyerUserId: string | number;
  sellerUserId: string | number;
  goodsId: string | number;
  goodsName: string;
  goodsGalleryUrls: string;
  price: number;
  payAmount: number;
  payType: string;
  serviceRegions: string;
  serviceTags: string;
  buyerRemark: string;
  sellerRemark: string;
  adminRemark: string;
  orderStatus: string;
  payExpireTime: string;
  deliveryType: string;
  deliveryVoucherText: string;
  deliveryVoucherOssIds: string;
  deliveryVoucherUrls: string;
  deliveryTime: string;
  receiveExpireTime: string;
  settleStatus: string;
  settleTime: string;
  refundAmount: number;
  refundRemark: string;
  refundStatus: string;
  refundApplyTime: string;
  refundAuditTime: string;
  refundAuditRemark: string;
  payTime: string;
  finishTime: string;
  cancelTime: string;
  refundTime: string;
  complaintStatus: string;
  complaintContent: string;
  complaintTime: string;
  complaintHandleRemark: string;
  complaintHandleTime: string;
  status: string;
  remark: string;
  createBy: string | number;
  createTime: string;
}

export interface OrderForm extends BaseEntity {
  id?: string | number;
  orderSn?: string;
  buyerUserId?: string | number;
  sellerUserId?: string | number;
  goodsId?: string | number;
  goodsName?: string;
  goodsGalleryUrls?: string;
  price?: number;
  payAmount?: number;
  payType?: string;
  serviceRegions?: string;
  serviceTags?: string;
  buyerRemark?: string;
  sellerRemark?: string;
  adminRemark?: string;
  orderStatus?: string;
  payExpireTime?: string;
  deliveryType?: string;
  deliveryVoucherText?: string;
  deliveryVoucherOssIds?: string[] | string;
  deliveryVoucherUrls?: string;
  deliveryTime?: string;
  receiveExpireTime?: string;
  settleStatus?: string;
  settleTime?: string;
  refundAmount?: number;
  refundRemark?: string;
  refundStatus?: string;
  refundApplyTime?: string;
  refundAuditTime?: string;
  refundAuditRemark?: string;
  payTime?: string;
  finishTime?: string;
  cancelTime?: string;
  refundTime?: string;
  complaintStatus?: string;
  complaintContent?: string;
  complaintTime?: string;
  complaintHandleRemark?: string;
  complaintHandleTime?: string;
  status?: string;
  remark?: string;
  actionPayType?: string;
  actionDeliveryVoucherText?: string;
  actionDeliveryVoucherOssIds?: string[] | string;
  actionDeliveryVoucherUrls?: string;
  actionRefundAmount?: number;
  actionRefundRemark?: string;
  actionRefundAuditStatus?: string;
  actionRefundAuditRemark?: string;
  actionComplaintContent?: string;
  actionComplaintHandleRemark?: string;
}

export interface OrderQuery extends PageQuery {
  orderSn?: string;
  buyerUserId?: string | number;
  sellerUserId?: string | number;
  goodsId?: string | number;
  goodsName?: string;
  orderStatus?: string;
  payType?: string;
  refundStatus?: string;
  complaintStatus?: string;
  serviceRegions?: string;
  serviceTags?: string;
  status?: string;
  params?: any;
}
